version: '3'
services:
  database:
    image: 403543998317.dkr.ecr.us-east-1.amazonaws.com/oracle:11g
    environment:
      - ORACLE_SID=xe
      - ORACLE_PDB=oracle
    volumes:
      - /tmp/oradata:/opt/oracle/oradata # persistent oracle database data.
    resources:
      limits:
        cpus: "0.1"
        memory: 50M
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
